run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    # not using
    - cyclop
    - exhaustivestruct
    - exhaustruct
    - funlen
    - gci
    - gofmt
    - gomnd
    - ifshort
    - ireturn
    - lll
    - nlreturn
    - varnamelen
    - wsl

    # to fix
    - paralleltest

    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
linters-settings:
  errcheck:
    check-type-assertions: true
  godot:
    capital: true
  gofumpt:
    extra-rules: true
  govet:
    check-shadowing: true
    enable-all: true
  misspell:
    locale: US
  revive:
    enable-all-rules: true
    rules:
      #fix
      - name: add-constant
        disabled: true

      #disabled
      - name: banned-characters
        disabled: true
      - name: file-header
        disabled: true
      - name: unused-receiver
        disabled: true

      - name: argument-limit
        arguments: [4]
      - name: cognitive-complexity
        arguments: [10]
        disabled: true
      - name: comment-spacings
        arguments: ["nolint"]
      - name: cyclomatic
        arguments: [5]
        disabled: true
      - name: function-result-limit
        arguments: [3]
      - name: function-length
        arguments: [10,0]
        disabled: true
      - name: line-length-limit
        arguments: [120]
      - name: max-public-structs
        arguments: [3]
  tagliatelle:
    case:
      rules:
        json: snake
  whitespace:
    multi-func: true
    multi-if: true