run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
#    - contextcheck #slow
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
#    - exhaustive # slow
    - exportloopref
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic # slow
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
#    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  errcheck:
    check-type-assertions: true
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
#      - style
  godot:
    capital: true
  gofumpt:
    extra-rules: true
  govet:
    check-shadowing: true
    enable-all: true
  misspell:
    locale: US
  revive:
    enable-all-rules: true
    rules:
      #fix
      - name: add-constant
        disabled: true

      #disabled
      - name: banned-characters
        disabled: true
      - name: file-header
        disabled: true
      - name: unused-receiver
        disabled: true

      - name: argument-limit
        arguments: [4]
      - name: cognitive-complexity
        arguments: [10]
        disabled: true
      - name: comment-spacings
        arguments: ["nolint"]
      - name: cyclomatic
        arguments: [10]
        disabled: true
      - name: function-result-limit
        arguments: [3]
      - name: function-length
        arguments: [40,60]
        disabled: true
      - name: line-length-limit
        arguments: [120]
      - name: max-public-structs
        arguments: [3]
  tagliatelle:
    case:
      rules:
        json: snake
  whitespace:
    multi-func: true
    multi-if: true