linters:
  enable-all: true
  disable:
    # not using
    - exhaustivestruct
    - exhaustruct
    - godot
    - gofmt
    - ireturn
    - loggercheck
    - nlreturn
    - varnamelen

    # revive handles
    - cyclop
    - funlen
    - gomnd
    - lll
    - wsl

    #slow
    - contextcheck
    - exhaustive
#    - gocritic

    # to fix
    - paralleltest

    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nilerr
    - nonamedreturns
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
linters-settings:
  errcheck:
    check-type-assertions: true
  errchkjson:
    check-error-free-encoding: true
    report-no-exported: false
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - commentedOutCode
  gofumpt:
    extra-rules: true
  govet:
    check-shadowing: true
    enable-all: true
  grouper:
    const-require-single-const: true
    import-require-single-import: true
    type-require-single-type: true
    var-require-single-var: true
  maligned:
    suggest-new: true
  misspell:
    locale: US
  revive:
    enable-all-rules: true
    rules:
      #disabled
      - name: banned-characters
        disabled: true
      - name: file-header
        disabled: true
      - name: unused-receiver
        disabled: true
      - name: comment-spacings
        disabled: true

      - name: argument-limit
        arguments: [5]
      - name: cognitive-complexity
        arguments: [22]
#      - name: comment-spacings
#        arguments: ["nolint"]
      - name: cyclomatic
        arguments: [15]
      - name: function-result-limit
        arguments: [3]
      - name: function-length
        arguments: [50,80]
      - name: line-length-limit
        arguments: [150]
      - name: max-public-structs
        arguments: [3]
  prealloc:
    for-loops: true
  tagliatelle:
    case:
      rules:
        json: snake
  usestdlibvars:
    time-weekday: true
    time-month: true
    time-layout: true
    crypto-hash: true
    default-rpc-path: true
    sql-isolation-level: true
    tls-signature-scheme: true
    constant-kind: true
  whitespace:
    multi-func: true
    multi-if: true
run:
  timeout: 5m
output:
  sort-results: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0