# https://taskfile.dev

version: '3'

dotenv: ['.env']

tasks:
  default:
    cmds:
      - task go:audit

  go:tidy:
    cmds:
      - sqlc compile --experimental
      - sqlc generate --experimental
      - ogen -no-client -no-webhook-client -no-webhook-server -generate-tests --target internal/oas -package oas --clean openapi.yaml
      - go mod tidy -v

  go:audit:
    deps: [go:tidy]
    cmds:
      - golangci-lint run --fix
      - go test -race -vet=off ./...
      - go mod verify

  go:upgrade:
    cmds:
      - go get -u ./...

  tilt:up:
    cmds:
      - tilt up

  tilt:down:
    cmds:
      - tilt down --delete-namespaces

  db:migrations:
    cmds:
      - dbmate -d "./db/migrations" --url $DATABASE_URL up

  db:psql:
    cmds:
      - psql $DATABASE_URL

  fly:deploy:
    cmds:
      - flyctl deploy

  fly:proxy:
    cmds:
      - flyctl proxy 5432 --app core-8585-db