// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Message   string             `json:"message"`
	UserID    int64              `json:"user_id"`
	Version   int32              `json:"version"`
}

type Token struct {
	Scope  string           `json:"scope"`
	Expiry pgtype.Timestamp `json:"expiry"`
	Hash   []byte           `json:"hash"`
	UserID int64            `json:"user_id"`
	Active bool             `json:"active"`
}

type User struct {
	ID           int64              `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash []byte             `json:"password_hash"`
	Activated    bool               `json:"activated"`
	Version      int32              `json:"version"`
}
