// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Message   string
	UserID    int64
	Version   int32
}

type Token struct {
	Hash   []byte
	UserID int64
	Expiry pgtype.Timestamptz
	Scope  string
}

type User struct {
	ID           int64
	CreatedAt    pgtype.Timestamptz
	Name         string
	Email        string
	PasswordHash []byte
	Activated    bool
	Version      int32
}
