// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ActivateUser implements ActivateUser operation.
//
// PATCH /v1/users/activate
func (UnimplementedHandler) ActivateUser(ctx context.Context, req *TokenRequest) (r ActivateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMessage implements DeleteMessage operation.
//
// DELETE /v1/messages/{id}
func (UnimplementedHandler) DeleteMessage(ctx context.Context, params DeleteMessageParams) (r DeleteMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMessage implements GetMessage operation.
//
// GET /v1/messages/{id}
func (UnimplementedHandler) GetMessage(ctx context.Context, params GetMessageParams) (r GetMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserMessages implements GetUserMessages operation.
//
// GET /v1/messages
func (UnimplementedHandler) GetUserMessages(ctx context.Context, params GetUserMessagesParams) (r GetUserMessagesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewAccessToken implements NewAccessToken operation.
//
// POST /v1/tokens/access
func (UnimplementedHandler) NewAccessToken(ctx context.Context, params NewAccessTokenParams) (r NewAccessTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewActivationToken implements NewActivationToken operation.
//
// POST /v1/tokens/activation
func (UnimplementedHandler) NewActivationToken(ctx context.Context, req *UserEmailRequest) (r NewActivationTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewMessage implements NewMessage operation.
//
// POST /v1/messages
func (UnimplementedHandler) NewMessage(ctx context.Context, req *MessageRequest) (r NewMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewPasswordResetToken implements NewPasswordResetToken operation.
//
// POST /v1/tokens/password-reset
func (UnimplementedHandler) NewPasswordResetToken(ctx context.Context, req *UserEmailRequest) (r NewPasswordResetTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewRefreshToken implements NewRefreshToken operation.
//
// POST /v1/tokens/refresh
func (UnimplementedHandler) NewRefreshToken(ctx context.Context, req *UserLoginRequest) (r NewRefreshTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewUser implements NewUser operation.
//
// POST /v1/users/register
func (UnimplementedHandler) NewUser(ctx context.Context, req *UserRequest) (r NewUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMessage implements UpdateMessage operation.
//
// PUT /v1/messages/{id}
func (UnimplementedHandler) UpdateMessage(ctx context.Context, req *MessageRequest, params UpdateMessageParams) (r UpdateMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUserPassword implements UpdateUserPassword operation.
//
// PATCH /v1/users/update-password
func (UnimplementedHandler) UpdateUserPassword(ctx context.Context, req *UpdateUserPasswordRequest) (r UpdateUserPasswordRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
