// Code generated by ogen, DO NOT EDIT.
package oas

type ActivateUserRes interface {
	activateUserRes()
}

type DeleteMessageRes interface {
	deleteMessageRes()
}

type GetMessageRes interface {
	getMessageRes()
}

type GetUserMessagesRes interface {
	getUserMessagesRes()
}

type NewAccessTokenRes interface {
	newAccessTokenRes()
}

type NewActivationTokenRes interface {
	newActivationTokenRes()
}

type NewMessageRes interface {
	newMessageRes()
}

type NewPasswordResetTokenRes interface {
	newPasswordResetTokenRes()
}

type NewRefreshTokenRes interface {
	newRefreshTokenRes()
}

type NewUserRes interface {
	newUserRes()
}

type UpdateMessageRes interface {
	updateMessageRes()
}

type UpdateUserPasswordRes interface {
	updateUserPasswordRes()
}
