name: Publish

on:
  push:
    tags: [ "-v*" ]
    branches: ['main']

permissions:
  contents: read
  packages: write

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yml
    with:
      go-version: ${{ vars.GO_VERSION }}

  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      go-version: ${{ vars.GO_VERSION }}

  build:
    uses: ./.github/workflows/reusable-build.yml
    needs: [lint, test]
    with:
      go-version: ${{ vars.GO_VERSION }}