name: Publish

on:
  push:
    tags: [ "-v*" ]
    branches: ['main']

permissions:
  contents: read
  packages: write

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yml

  test:
    uses: ./.github/workflows/reusable-test.yml

  build:
    uses: ./.github/workflows/reusable-build.yml
    needs: [lint, test]