name: "Publish"

on:
  push:
    tags: [ "-v*" ]
    branches: ['main']

permissions:
  contents: read
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/reusable-lint.yml

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/reusable-test.yml

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: ./.github/workflows/reusable-build.yml
