name: Publish

on:
  push:
    tags: [ "-v*" ]
    branches: ['main']
    
env:
  GO_VERSION: "1.20.X"

permissions:
  contents: read
  packages: write

jobs:
  lint:
    uses: ./.github/workflows/reusable/lint.yml
    with:
      go-version: ${{ vars.GO_VERSION }}

  test:
    uses: ./.github/workflows/reusable/test.yml
    with:
      go-version: ${{ vars.GO_VERSION }}

  build-image:
    uses: ./.github/workflows/reusable/build_image.yml
    with:
      go-version: ${{ vars.GO_VERSION }}