name: Publish

on:
  push:
    tags: [ "-v*" ]
    branches: ['main']
    
env:
  GO_VERSION: "1.20.X"

permissions:
  contents: read
  packages: write

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yml
    with:
      go-version: ${{ env.GO_VERSION }}

  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      go-version: ${{ env.GO_VERSION }}

  build-image:
    uses: ./.github/workflows/reusable-build-image.yml
    needs: [lint, test]
    with:
      go-version: ${{ env.GO_VERSION }}