name: "Verify PR"

on:
  pull_request:
env:
  GO_VERSION: "1.20.X"

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yml
    with:
      go-version: ${{ env.GO_VERSION }}

  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      go-version: ${{ env.GO_VERSION }}